version: 0.2
phases:
    install:
        commands:
            - 'yarn -v'
            - 'yarn install'
            - 'yarn build'
artifacts:
    files:
        - '*.*'
cache:
    paths:
        - node_modules
