version: 0.2
phases:
    install:
        commands:
            - 'yarn -v'
            - 'yarn install'
            - 'yarn build'
            - aws s3 sync --acl public-read --delete public/ "s3://${BUCKET_NAME}"
cache:
    paths:
        - node_modules
