version: 0.2
phases:
    install:
        commands:
            - npm install -g yarn
            - 'yarn -v'
            - 'yarn install'
            - 'yarn build'
            - aws s3 sync --acl public-read --delete build/ "s3://${BUCKET_NAME}"
cache:
    paths:
        - node_modules
