version: 0.2
phases:
    install:
        commands:
            - yarn
            - yarn build
            - aws s3 sync --acl public-read --delete build/ "s3://${BUCKET_NAME}"
cache:
    paths:
        - node_modules
